import type { RoundTableChatMessage, ThinkTankAnalysis } from "@/components/roundtable/types";
import { sortDisplayNames } from "@/lib/figure-sort";

function formatTranscript(messages: RoundTableChatMessage[]): string {
  return messages
    .map((m) => {
      if (m.role === "user") {
        const text = m.content.replace(/^Moderator:\s*/i, "");
        return `### Round Table Moderator\n\n${text}\n`;
      }
      return `### ${m.figureName ?? "Figure"} (${m.era ?? ""})\n\n> ${m.content}\n`;
    })
    .join("\n");
}

function formatAnalysisSections(analysis: ThinkTankAnalysis): string {
  return [
    "## Consensus",
    analysis.consensus,
    "",
    "## Disagreements",
    analysis.disagreements,
    "",
    "## Risks",
    analysis.risks,
    "",
    "## Recommendations",
    analysis.recommendations,
    "",
    "## Executive Summary",
    analysis.executiveSummary,
  ].join("\n");
}

export function buildDebateMarkdown(params: {
  topicTitle: string;
  topicFull?: string;
  messages: RoundTableChatMessage[];
  analysis?: ThinkTankAnalysis | null;
  participantNames?: string[];
}): string {
  const { topicTitle, topicFull, messages, analysis, participantNames } = params;
  const lines: string[] = [
    `# FMS Think Tank — Historical Round Table`,
    "",
    `**Topic:** ${topicTitle}`,
  ];

  if (topicFull && topicFull !== topicTitle) {
    lines.push("", topicFull);
  }

  if (participantNames?.length) {
    lines.push(
      "",
      `**Participants:** ${sortDisplayNames(participantNames).join(", ")}`,
    );
  }

  lines.push("", "---", "", "## Transcript", "", formatTranscript(messages));

  if (analysis) {
    lines.push("", "---", "", "## Think Tank Analysis", "", formatAnalysisSections(analysis));
  }

  lines.push("", "---", "", "*Generated by FMS Expert Agents — Historical Round Table*");
  return lines.join("\n");
}

export function buildResearchBriefMarkdown(params: {
  topicTitle: string;
  analysis: ThinkTankAnalysis;
  messages: RoundTableChatMessage[];
}): string {
  const { topicTitle, analysis, messages } = params;
  const exchangeCount = messages.filter((m) => m.role === "assistant").length;

  return [
    `# Research Brief`,
    "",
    `**Subject:** ${topicTitle}`,
    `**Date:** ${new Date().toLocaleDateString("en-GB", { dateStyle: "long" })}`,
    `**Exchanges reviewed:** ${exchangeCount}`,
    "",
    "## Executive Summary",
    analysis.executiveSummary,
    "",
    "## Key Findings",
    "### Areas of Consensus",
    analysis.consensus,
    "",
    "### Points of Contention",
    analysis.disagreements,
    "",
    "## Risk Assessment",
    analysis.risks,
    "",
    "## Policy Implications",
    analysis.recommendations,
    "",
    "---",
    "*FMS Think Tank — Historical Round Table Research Brief*",
  ].join("\n");
}

export function buildExecutiveSummaryMarkdown(params: {
  topicTitle: string;
  analysis: ThinkTankAnalysis;
  participantNames?: string[];
}): string {
  const { topicTitle, analysis, participantNames } = params;
  const lines: string[] = [
    `# Executive Summary`,
    "",
    `**Topic:** ${topicTitle}`,
    `**Date:** ${new Date().toLocaleDateString("en-GB", { dateStyle: "long" })}`,
  ];
  if (participantNames?.length) {
    lines.push(
      "",
      `**Participants:** ${sortDisplayNames(participantNames).join(", ")}`,
    );
  }
  lines.push(
    "",
    analysis.executiveSummary,
    "",
    "## Consensus Highlights",
    analysis.consensus,
    "",
    "## Key Recommendations",
    analysis.recommendations,
    "",
    "---",
    "*FMS Think Tank — Historical Round Table Executive Summary*",
  );
  return lines.join("\n");
}

export function buildPolicyMemoMarkdown(params: {
  topicTitle: string;
  analysis: ThinkTankAnalysis;
}): string {
  const { topicTitle, analysis } = params;

  return [
    `# POLICY MEMORANDUM`,
    "",
    `**TO:** Senior Leadership`,
    `**FROM:** FMS Think Tank — Round Table Analysis`,
    `**RE:** ${topicTitle}`,
    `**DATE:** ${new Date().toLocaleDateString("en-GB", { dateStyle: "long" })}`,
    "",
    "## Summary",
    analysis.executiveSummary,
    "",
    "## Recommended Actions",
    analysis.recommendations,
    "",
    "## Risks & Mitigations",
    analysis.risks,
    "",
    "## Dissenting Views (for awareness)",
    analysis.disagreements,
    "",
    "## Supporting Consensus",
    analysis.consensus,
    "",
    "---",
    "*Confidential working document — FMS Expert Agents*",
  ].join("\n");
}

export function downloadTextFile(filename: string, content: string, mime = "text/markdown"): void {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function openPrintView(html: string, title: string): void {
  const printWindow = window.open("", "_blank", "noopener,noreferrer");
  if (!printWindow) return;

  printWindow.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <style>
    @page { margin: 2cm; }
    body {
      font-family: Georgia, "Times New Roman", serif;
      font-size: 11pt;
      line-height: 1.5;
      color: #1a1208;
      max-width: 720px;
      margin: 0 auto;
      padding: 1rem;
    }
    h1 { font-size: 18pt; border-bottom: 1px solid #c4a574; padding-bottom: 0.5rem; }
    h2 { font-size: 13pt; margin-top: 1.5rem; color: #6b5c3e; }
    h3 { font-size: 11pt; margin-top: 1rem; }
    blockquote {
      margin: 0.5rem 0 1rem 1rem;
      padding-left: 0.75rem;
      border-left: 3px solid #8b6914;
      font-style: italic;
    }
    .moderator {
      background: #f4ead5;
      padding: 0.75rem 1rem;
      border-radius: 4px;
      margin: 1rem 0;
    }
    hr { border: none; border-top: 1px solid #c4a574; margin: 1.5rem 0; }
    @media print {
      body { padding: 0; }
    }
  </style>
</head>
<body>${html}</body>
</html>`);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 300);
}

export function markdownToPrintHtml(markdown: string): string {
  return markdown
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(.+)$/gm, (line) => {
      if (line.startsWith("<")) return line;
      return line;
    });
}
